service: serverless-example

plugins:
  - ../dist/src/index.js
  - serverless-offline
package:
  individually: true

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: src/handlers/hello.default
    events:
      - http:
          path: hello
          method: get
  world:
    handler: src/handlers/world.default
    events:
      - http:
          path: world
          method: get
